# Conexion a la base de datos

spring:
  datasource:
    url: jdbc:oracle:thin:@//localhost:1521/FREE
    username: system
    password: Ora1234
    hikari:
      connection-timeout: 20000
      maximum-pool-size: 5